---
title: "index"
author: "James Fahlbusch"
date: "November 30, 2017"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#this includes the library but by putting it in this chunk it is
#not shown
library(tidyverse)
```

## Scatterplot

```{r scatterplot}
#data()

g <- ggplot(data = mpg, aes(x = displ,y = hwy))
g + geom_point()

```

### I need color!
```{r color, echo=TRUE}
g + geom_point(aes(color = class))
```

### Get me some shapes!
```{r shape, echo=TRUE}
g + geom_point(aes(shape = class))
```

### Get me some sizes!
```{r sizes, echo=TRUE}
g + geom_point(aes(size = class))
```
## Including Plots

You can also embed plots, for example:

```{r ctyhwy, echo=TRUE}
ggplot(data=mpg, aes(x=cty, y=hwy,size=class,color=class)) + geom_point(alpha = 0.2)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


### Multiple
```{r multiple, echo=FALSE}
ggplot(data=mpg, aes(x=displ, y=hwy))+ 
geom_point()+
geom_smooth()+
labs(title = "Relationship between engine sixe and MPG",
     x= "Highway MPG",
     y="Engine Displacement")+
  theme_classic()
```


## Data Wrangling with `dplyr`
```{r dw, echo=TRUE}
library(tidyverse)
gapminder <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

head(gapminder)
tail(gapminder)
summary(gapminder)
#check out the structure of your data
str(gapminder)
#column names
names(gapminder)
#dimensions of dataframe
dim(gapminder) #[1]
ncol(gapminder)
nrow(gapminder)
c(nrow(gapminder), ncol(gapminder))

```
### Using filters
```{r dwf, echo=TRUE}
#mean life expectancy in sweden
mean(filter(gapminder, country == "Sweden")$lifeExp)


```

### Pipe Operator ` %>% `
```{r pipe, echo = TRUE}
gapminder %>% head(3)

gapminder %>% 
  group_by(country) %>% 
  #filter(country == "Sweden") %>% 
  summarize(mean(lifeExp)) 

gapminder %>% 
  select(year, lifeExp) %>% 
  tail()

gapminder %>% 
  filter(country == "Cambodia",
         year == 2002) %>% 
  select(country, year, pop, gdpPercap)

gapminder %>% 
  filter(country == "Cambodia") %>% 
  select(-continent, -lifeExp)

# use mutate to add a calculated column
gapminder <- gapminder %>% 
  mutate(gdp = pop * gdpPercap,
         index = 1:nrow(gapminder))


gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  group_by(country) %>% 
  summarize(maxGDP = max(gdpPercap))
  
gapminder %>% 
  group_by(country) %>% 
  mutate(maxGDP = max(gdpPercap)) %>% 
  filter(gdpPercap == max(gdpPercap))

gapminder %>% 
  group_by(year) %>% 
  mutate(maxGDP = max(gdpPercap)) %>% 
  filter(gdpPercap == max(gdpPercap)) %>% 
  arrange(year)
  
gapminder %>% 
  group_by(year) %>% 
  mutate(minGDP = min(gdpPercap)) %>% 
  filter(gdpPercap == min(gdpPercap)) %>% 
  arrange(year)

```
## Joining Datasets
```{r co2}
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")
co2 %>% head()
co2 %>% str()

gap_2007 <-  gapminder %>% 
  filter(year==2007)

# left join 
lj <-  left_join(gap_2007, co2, by = "country")
lj %>%  dim()
# lj %>% View()

# right join
rj <-  right_join(gap_2007,co2)
rj %>%  dim()
# rj %>% View()
```


## TIDYR BASICS

```{r tidy}
# making wide data narrow and vice versa

AirPassengers
mpg

gap_wide <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv")

## use gather
#turn gap_wide into long format
gap_long <- gap_wide %>%
  gather(key = obstype_year,
         value = obs_values,
         dplyr::starts_with("pop"),
         dplyr::starts_with("lifeExp"),
         dplyr::starts_with("gdpPercap"))

## use separate 
gap_long <- gap_wide %>%
  gather(key = obstype_year,
         value = obs_values,
         -continent, -country) %>% 
  separate(obstype_year,
           into = c("obs_type", "year"),
           sep = "_",
           convert = TRUE)


```

### Plot long form data
```{r plotLF}

life_df <- gap_long %>% 
  filter(obs_type == "lifeExp", 
         continent == "Americas")

ggplot(life_df,aes(x= year, y = obs_values, color = country)) + 
  geom_line()


meanLE_df <- gap_long %>% 
  filter(obs_type == "lifeExp",
         year >= 1982,
         year <= 2007) %>% 
  group_by(continent, year) %>% 
  summarize(mean = mean(obs_values))

ggplot(meanLE_df,aes(x= year, y = mean, color = continent)) + 
  geom_line()

```


```{r spread}

gap_normal <- gap_long %>% 
  spread(key = obs_type,
         value = obs_values)


```


